language: node_js

sudo: required
services:
  - docker

script:
  - docker build -t siluok3/node-backend ./backend
  - docker images siluok3/node-backend

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push siluok3/node-backend
  on:
    branch: master