version: '3.8'
services: 
  fullstack-webapp:
    container_name: node-backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    stdin_open: true
    container_name: react-frontend
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # links:
    #   - "fullstack-webapp"
    volumes:
      - "./frontend:/client"
      - "/client/node_modules"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"