version: '3.8'
services: 
  fullstack-webapp:
    container_name: fullstack-webapp
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: client
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - "fullstack-webapp"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"